name: Test Upload Files

on:
  push:
    branches: ["main"]

jobs:
  test-upload-files:
    name: Setup, Push
    runs-on: ubuntu-latest
    environment: test

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Changed Files To be Uploaded
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $CHANGED_FILES; do
            if [ -f "$file" ] && ! git check-ignore -q "$file"; then
              echo "Uploading $file to bucket"
            fi
          done

